# --------------------
# stage 1
# --------------------

FROM golang:1.19 AS builder

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0
ENV GO111MODULE=on

WORKDIR /workdir

# install dependencies
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# build
COPY . .
RUN go build -o /workdir/app .

# --------------------
# stage 2
# --------------------

FROM alpine:3.14

COPY --from=builder /workdir/app /usr/local/bin/app

EXPOSE 8888
CMD ["/app"]
